/*
 * Surfing/kiting spot
 * Restful API for management of Surfing/kitting spot.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Item;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * NewItem
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-04-03T23:35:29.473682+02:00[Europe/Warsaw]")
public class NewItem extends Item {
  @SerializedName("id")
  private BigDecimal newItemId = null;

  @SerializedName("createdAt")
  private String createdAt = null;

  public NewItem newItemId(BigDecimal newItemId) {
    this.newItemId = newItemId;
    return this;
  }

   /**
   * Get newItemId
   * @return newItemId
  **/
  @Schema(description = "")
  public BigDecimal getNewItemId() {
    return newItemId;
  }

  public void setNewItemId(BigDecimal newItemId) {
    this.newItemId = newItemId;
  }

  public NewItem createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Created date
   * @return createdAt
  **/
  @Schema(required = true, description = "Created date")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NewItem newItem = (NewItem) o;
    return Objects.equals(this.newItemId, newItem.newItemId) &&
        Objects.equals(this.createdAt, newItem.createdAt) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(newItemId, createdAt, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NewItem {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    newItemId: ").append(toIndentedString(newItemId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
