/*
 * Surfing/kiting spot
 * Restful API for management of Surfing/kitting spot.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.ErrorModel;
import io.swagger.client.model.GetStock;
import io.swagger.client.model.Item;
import io.swagger.client.model.NewItem;
import io.swagger.client.model.Stock;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for StocksApi
 */
@Ignore
public class StocksApiTest {

    private final StocksApi api = new StocksApi();

    /**
     * 
     *
     * Creates a new stock. Duplicates are not allowed
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void addStockTest() throws Exception {
        Stock body = null;
        NewItem response = api.addStock(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * deletes a single stock based on the ID supplied
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteStockTest() throws Exception {
        Long id = null;
        Item response = api.deleteStock(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * This endpoints are related with the stocks model of the application.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getStockTest() throws Exception {
        Long id = null;
        GetStock response = api.getStock(id);

        // TODO: test validations
    }
    /**
     * 
     *
     * This endpoint returns all stocks from the database.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getStocksTest() throws Exception {
        String responsiblePerson = null;
        String name = null;
        List<GetStock> response = api.getStocks(responsiblePerson, name);

        // TODO: test validations
    }
    /**
     * 
     *
     * Update stock
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateStockTest() throws Exception {
        Long id = null;
        Item response = api.updateStock(id);

        // TODO: test validations
    }
}
