/*
 * Surfing/kiting spot
 * Restful API for management of Surfing/kitting spot.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import io.gsonfire.GsonFireBuilder;
import io.gsonfire.PostProcessor;
import io.gsonfire.TypeSelector;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.internal.bind.util.ISO8601Utils;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import org.threeten.bp.LocalDate;
import org.threeten.bp.OffsetDateTime;
import org.threeten.bp.format.DateTimeFormatter;

import io.swagger.client.model.*;

import java.io.IOException;
import java.io.StringReader;
import java.lang.reflect.Type;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.ParsePosition;
import java.util.Date;
import java.util.Map;
import java.util.HashMap;

public class JSON {
    private Gson gson;
    private boolean isLenientOnJson = false;
    private DateTypeAdapter dateTypeAdapter = new DateTypeAdapter();
    private SqlDateTypeAdapter sqlDateTypeAdapter = new SqlDateTypeAdapter();
    private OffsetDateTimeTypeAdapter offsetDateTimeTypeAdapter = new OffsetDateTimeTypeAdapter();
    private LocalDateTypeAdapter localDateTypeAdapter = new LocalDateTypeAdapter();

    public static GsonBuilder createGson() {
        GsonFireBuilder fireBuilder = new GsonFireBuilder()
          .registerTypeSelector(User.class, new TypeSelector<User>() {
            @Override
            public Class<? extends User> getClassForElement(JsonElement readElement) {
                Map<String, Class<? extends User>> classByDiscriminatorValue = new HashMap<>();
                    classByDiscriminatorValue.put("AddUser".toUpperCase(), AddUser.class);
                    classByDiscriminatorValue.put("User".toUpperCase(), User.class);
                return getClassByDiscriminator(
                            classByDiscriminatorValue,
                            getDiscriminatorValue(readElement, ""));
            }
          })
          .registerPostProcessor(User.class, new PostProcessor<User>() {
              @Override
              public void postDeserialize(User result, JsonElement src, Gson gson) {

              }

              @Override
              public void postSerialize(JsonElement result, User src, Gson gson) {
                  Map<Class<? extends User>, String> discriminatorValueByClass = new HashMap<>();
                      discriminatorValueByClass.put(AddUser.class, "AddUser");
                      discriminatorValueByClass.put(User.class, "User");
                  if(result instanceof JsonObject)
                  {
                      if(!((JsonObject) result).has(""))
                      {
                          ((JsonObject) result).addProperty("", discriminatorValueByClass.get(src.getClass()));
                      }
                  }
              }
          })
          .registerTypeSelector(Order.class, new TypeSelector<Order>() {
            @Override
            public Class<? extends Order> getClassForElement(JsonElement readElement) {
                Map<String, Class<? extends Order>> classByDiscriminatorValue = new HashMap<>();
                    classByDiscriminatorValue.put("GetOrder".toUpperCase(), GetOrder.class);
                    classByDiscriminatorValue.put("Order".toUpperCase(), Order.class);
                return getClassByDiscriminator(
                            classByDiscriminatorValue,
                            getDiscriminatorValue(readElement, ""));
            }
          })
          .registerPostProcessor(Order.class, new PostProcessor<Order>() {
              @Override
              public void postDeserialize(Order result, JsonElement src, Gson gson) {

              }

              @Override
              public void postSerialize(JsonElement result, Order src, Gson gson) {
                  Map<Class<? extends Order>, String> discriminatorValueByClass = new HashMap<>();
                      discriminatorValueByClass.put(GetOrder.class, "GetOrder");
                      discriminatorValueByClass.put(Order.class, "Order");
                  if(result instanceof JsonObject)
                  {
                      if(!((JsonObject) result).has(""))
                      {
                          ((JsonObject) result).addProperty("", discriminatorValueByClass.get(src.getClass()));
                      }
                  }
              }
          })
          .registerTypeSelector(Product.class, new TypeSelector<Product>() {
            @Override
            public Class<? extends Product> getClassForElement(JsonElement readElement) {
                Map<String, Class<? extends Product>> classByDiscriminatorValue = new HashMap<>();
                    classByDiscriminatorValue.put("GetProduct".toUpperCase(), GetProduct.class);
                    classByDiscriminatorValue.put("Product".toUpperCase(), Product.class);
                return getClassByDiscriminator(
                            classByDiscriminatorValue,
                            getDiscriminatorValue(readElement, ""));
            }
          })
          .registerPostProcessor(Product.class, new PostProcessor<Product>() {
              @Override
              public void postDeserialize(Product result, JsonElement src, Gson gson) {

              }

              @Override
              public void postSerialize(JsonElement result, Product src, Gson gson) {
                  Map<Class<? extends Product>, String> discriminatorValueByClass = new HashMap<>();
                      discriminatorValueByClass.put(GetProduct.class, "GetProduct");
                      discriminatorValueByClass.put(Product.class, "Product");
                  if(result instanceof JsonObject)
                  {
                      if(!((JsonObject) result).has(""))
                      {
                          ((JsonObject) result).addProperty("", discriminatorValueByClass.get(src.getClass()));
                      }
                  }
              }
          })
          .registerTypeSelector(Relation.class, new TypeSelector<Relation>() {
            @Override
            public Class<? extends Relation> getClassForElement(JsonElement readElement) {
                Map<String, Class<? extends Relation>> classByDiscriminatorValue = new HashMap<>();
                    classByDiscriminatorValue.put("GetRelation".toUpperCase(), GetRelation.class);
                    classByDiscriminatorValue.put("Relation".toUpperCase(), Relation.class);
                return getClassByDiscriminator(
                            classByDiscriminatorValue,
                            getDiscriminatorValue(readElement, ""));
            }
          })
          .registerPostProcessor(Relation.class, new PostProcessor<Relation>() {
              @Override
              public void postDeserialize(Relation result, JsonElement src, Gson gson) {

              }

              @Override
              public void postSerialize(JsonElement result, Relation src, Gson gson) {
                  Map<Class<? extends Relation>, String> discriminatorValueByClass = new HashMap<>();
                      discriminatorValueByClass.put(GetRelation.class, "GetRelation");
                      discriminatorValueByClass.put(Relation.class, "Relation");
                  if(result instanceof JsonObject)
                  {
                      if(!((JsonObject) result).has(""))
                      {
                          ((JsonObject) result).addProperty("", discriminatorValueByClass.get(src.getClass()));
                      }
                  }
              }
          })
          .registerTypeSelector(Stock.class, new TypeSelector<Stock>() {
            @Override
            public Class<? extends Stock> getClassForElement(JsonElement readElement) {
                Map<String, Class<? extends Stock>> classByDiscriminatorValue = new HashMap<>();
                    classByDiscriminatorValue.put("GetStock".toUpperCase(), GetStock.class);
                    classByDiscriminatorValue.put("Stock".toUpperCase(), Stock.class);
                return getClassByDiscriminator(
                            classByDiscriminatorValue,
                            getDiscriminatorValue(readElement, ""));
            }
          })
          .registerPostProcessor(Stock.class, new PostProcessor<Stock>() {
              @Override
              public void postDeserialize(Stock result, JsonElement src, Gson gson) {

              }

              @Override
              public void postSerialize(JsonElement result, Stock src, Gson gson) {
                  Map<Class<? extends Stock>, String> discriminatorValueByClass = new HashMap<>();
                      discriminatorValueByClass.put(GetStock.class, "GetStock");
                      discriminatorValueByClass.put(Stock.class, "Stock");
                  if(result instanceof JsonObject)
                  {
                      if(!((JsonObject) result).has(""))
                      {
                          ((JsonObject) result).addProperty("", discriminatorValueByClass.get(src.getClass()));
                      }
                  }
              }
          })
          .registerTypeSelector(NewItem.class, new TypeSelector<NewItem>() {
            @Override
            public Class<? extends NewItem> getClassForElement(JsonElement readElement) {
                Map<String, Class<? extends NewItem>> classByDiscriminatorValue = new HashMap<>();
                    classByDiscriminatorValue.put("GetUser".toUpperCase(), GetUser.class);
                    classByDiscriminatorValue.put("NewItem".toUpperCase(), NewItem.class);
                return getClassByDiscriminator(
                            classByDiscriminatorValue,
                            getDiscriminatorValue(readElement, ""));
            }
          })
          .registerPostProcessor(NewItem.class, new PostProcessor<NewItem>() {
              @Override
              public void postDeserialize(NewItem result, JsonElement src, Gson gson) {

              }

              @Override
              public void postSerialize(JsonElement result, NewItem src, Gson gson) {
                  Map<Class<? extends NewItem>, String> discriminatorValueByClass = new HashMap<>();
                      discriminatorValueByClass.put(GetUser.class, "GetUser");
                      discriminatorValueByClass.put(NewItem.class, "NewItem");
                  if(result instanceof JsonObject)
                  {
                      if(!((JsonObject) result).has(""))
                      {
                          ((JsonObject) result).addProperty("", discriminatorValueByClass.get(src.getClass()));
                      }
                  }
              }
          })
          .registerTypeSelector(Item.class, new TypeSelector<Item>() {
            @Override
            public Class<? extends Item> getClassForElement(JsonElement readElement) {
                Map<String, Class<? extends Item>> classByDiscriminatorValue = new HashMap<>();
                    classByDiscriminatorValue.put("NewItem".toUpperCase(), NewItem.class);
                    classByDiscriminatorValue.put("Item".toUpperCase(), Item.class);
                return getClassByDiscriminator(
                            classByDiscriminatorValue,
                            getDiscriminatorValue(readElement, ""));
            }
          })
          .registerPostProcessor(Item.class, new PostProcessor<Item>() {
              @Override
              public void postDeserialize(Item result, JsonElement src, Gson gson) {

              }

              @Override
              public void postSerialize(JsonElement result, Item src, Gson gson) {
                  Map<Class<? extends Item>, String> discriminatorValueByClass = new HashMap<>();
                      discriminatorValueByClass.put(NewItem.class, "NewItem");
                      discriminatorValueByClass.put(Item.class, "Item");
                  if(result instanceof JsonObject)
                  {
                      if(!((JsonObject) result).has(""))
                      {
                          ((JsonObject) result).addProperty("", discriminatorValueByClass.get(src.getClass()));
                      }
                  }
              }
          })
        ;
        return fireBuilder.createGsonBuilder();
    }

    private static String getDiscriminatorValue(JsonElement readElement, String discriminatorField) {
        JsonElement element = readElement.getAsJsonObject().get(discriminatorField);
        if(null == element) {
            throw new IllegalArgumentException("missing discriminator field: <" + discriminatorField + ">");
        }
        return element.getAsString();
    }

    private static <T> Class<? extends T> getClassByDiscriminator(Map<String, Class<? extends T>> classByDiscriminatorValue, String discriminatorValue) {
        Class<? extends T> clazz = classByDiscriminatorValue.get(discriminatorValue.toUpperCase());
        if(null == clazz) {
            throw new IllegalArgumentException("cannot determine model class of name: <" + discriminatorValue + ">");
        }
        return clazz;
    }

    public JSON() {
        gson = createGson()
            .registerTypeAdapter(Date.class, dateTypeAdapter)
            .registerTypeAdapter(java.sql.Date.class, sqlDateTypeAdapter)
            .registerTypeAdapter(OffsetDateTime.class, offsetDateTimeTypeAdapter)
            .registerTypeAdapter(LocalDate.class, localDateTypeAdapter)
            .create();
    }

    /**
     * Get Gson.
     *
     * @return Gson
     */
    public Gson getGson() {
        return gson;
    }

    /**
     * Set Gson.
     *
     * @param gson Gson
     * @return JSON
     */
    public JSON setGson(Gson gson) {
        this.gson = gson;
        return this;
    }

    public JSON setLenientOnJson(boolean lenientOnJson) {
        isLenientOnJson = lenientOnJson;
        return this;
    }

    /**
     * Serialize the given Java object into JSON string.
     *
     * @param obj Object
     * @return String representation of the JSON
     */
    public String serialize(Object obj) {
        return gson.toJson(obj);
    }

    /**
     * Deserialize the given JSON string to Java object.
     *
     * @param <T>        Type
     * @param body       The JSON string
     * @param returnType The type to deserialize into
     * @return The deserialized Java object
     */
    @SuppressWarnings("unchecked")
    public <T> T deserialize(String body, Type returnType) {
        try {
            if (isLenientOnJson) {
                JsonReader jsonReader = new JsonReader(new StringReader(body));
                // see https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/stream/JsonReader.html#setLenient(boolean)
                jsonReader.setLenient(true);
                return gson.fromJson(jsonReader, returnType);
            } else {
                return gson.fromJson(body, returnType);
            }
        } catch (JsonParseException e) {
            // Fallback processing when failed to parse JSON form response body:
            // return the response body string directly for the String return type;
            if (returnType.equals(String.class))
                return (T) body;
            else throw (e);
        }
    }

    /**
     * Gson TypeAdapter for JSR310 OffsetDateTime type
     */
    public static class OffsetDateTimeTypeAdapter extends TypeAdapter<OffsetDateTime> {

        private DateTimeFormatter formatter;

        public OffsetDateTimeTypeAdapter() {
            this(DateTimeFormatter.ISO_OFFSET_DATE_TIME);
        }

        public OffsetDateTimeTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, OffsetDateTime date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public OffsetDateTime read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    if (date.endsWith("+0000")) {
                        date = date.substring(0, date.length()-5) + "Z";
                    }
                    return OffsetDateTime.parse(date, formatter);
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 LocalDate type
     */
    public class LocalDateTypeAdapter extends TypeAdapter<LocalDate> {

        private DateTimeFormatter formatter;

        public LocalDateTypeAdapter() {
            this(DateTimeFormatter.ISO_LOCAL_DATE);
        }

        public LocalDateTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, LocalDate date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public LocalDate read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    return LocalDate.parse(date, formatter);
            }
        }
    }

    public JSON setOffsetDateTimeFormat(DateTimeFormatter dateFormat) {
        offsetDateTimeTypeAdapter.setFormat(dateFormat);
        return this;
    }

    public JSON setLocalDateFormat(DateTimeFormatter dateFormat) {
        localDateTypeAdapter.setFormat(dateFormat);
        return this;
    }

    /**
     * Gson TypeAdapter for java.sql.Date type
     * If the dateFormat is null, a simple "yyyy-MM-dd" format will be used
     * (more efficient than SimpleDateFormat).
     */
    public static class SqlDateTypeAdapter extends TypeAdapter<java.sql.Date> {

        private DateFormat dateFormat;

        public SqlDateTypeAdapter() {
        }

        public SqlDateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, java.sql.Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = date.toString();
                }
                out.value(value);
            }
        }

        @Override
        public java.sql.Date read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    try {
                        if (dateFormat != null) {
                            return new java.sql.Date(dateFormat.parse(date).getTime());
                        }
                        return new java.sql.Date(ISO8601Utils.parse(date, new ParsePosition(0)).getTime());
                    } catch (ParseException e) {
                        throw new JsonParseException(e);
                    }
            }
        }
    }

    /**
     * Gson TypeAdapter for java.util.Date type
     * If the dateFormat is null, ISO8601Utils will be used.
     */
    public static class DateTypeAdapter extends TypeAdapter<Date> {

        private DateFormat dateFormat;

        public DateTypeAdapter() {
        }

        public DateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = ISO8601Utils.format(date, true);
                }
                out.value(value);
            }
        }

        @Override
        public Date read(JsonReader in) throws IOException {
            try {
                switch (in.peek()) {
                    case NULL:
                        in.nextNull();
                        return null;
                    default:
                        String date = in.nextString();
                        try {
                            if (dateFormat != null) {
                                return dateFormat.parse(date);
                            }
                            return ISO8601Utils.parse(date, new ParsePosition(0));
                        } catch (ParseException e) {
                            throw new JsonParseException(e);
                        }
                }
            } catch (IllegalArgumentException e) {
                throw new JsonParseException(e);
            }
        }
    }

    public JSON setDateFormat(DateFormat dateFormat) {
        dateTypeAdapter.setFormat(dateFormat);
        return this;
    }

    public JSON setSqlDateFormat(DateFormat dateFormat) {
        sqlDateTypeAdapter.setFormat(dateFormat);
        return this;
    }

}
